config/routes.rb
Gradebook::Application.routes.draw do
  match 'reporting/:course_id' => 'reporting#show'
  
  get "courses/index"

  match 'gradebooks/:course_id/table' => 'gradebooks#table'
  match 'submit_grade' => 'assignment_grades#submit'

  resources :grade_scales
  resources :courses
  resources :gradebook_settings

  match 'gradebooks/:course_id', :to => 'gradebooks#show'
  match 'gradebooks/:course_id/assignments', :to => "assignments#new"
  resources :assignment_grades
  resources :assignments, :except => [:index]
  match 'assignments/update/' => 'assignments#update', :via => :post

  match 'gradebooks/:course_id/assignments/update' => 'assignments#update' , :via => :post
  match 'gradebooks/:course_id/:assignment_id/edit' => 'assignments#edit'
  match 'gradebooks/:course_id/report' => 'gradebooks#report'

  match 'gradebooks/grading_scale/:course_id' => 'grade_scales#scale'
  match 'gradebooks/assignments/:id/update' => 'assignments#update_assignment_grade', :via => :put
  match 'gradebooks/assignments/:id/report' => 'assignments#grade_report'
  match 'gradebooks/assignments/:id/comment' => 'assignments#comment_submit', :via => :put
  match 'gradebooks/assignments/:id/manual_grade' => 'grade_scales#grade', :via => :put
  match 'gradebooks/:course_id/weight' => 'gradebooks#weight'
  match 'gradebooks/settings/:settings_id/weight' => 'gradebook_settings#update_weight', :via => :put

  match 'gradebooks/:course_id/student/:student_id' => 'gradebooks#student_view'

  match 'gradebooks/:course_id/:student_id/course_grade' => 'gradebooks#update_course_grade', :via => :put

  match 'attendance/:course_id/student/:student_id/:date', :to => "attendance_records#update_student", :via => :post, :as => "update_student_attendance"
  match 'attendance/:course_id/student/:student_id/', :to => "attendance_records#student_record", :via => :get, :as => "student_attendance"
  match 'attendance/:course_id(/:date)', :to => "attendance_records#show", :as => "course_attendance"

end

app/models/assignment.rb
class Assignment
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActionView::Helpers::NumberHelper

  cache
  
  belongs_to :assignment_type
  index :assignment_type_id

  field :course_id, :type => Integer
  index :course_id

  field :name, :type => String
  field :point_value, :type => Integer
  field :date_due, :type => Date

  field :average, :type => Float
  #All grades accessible from here
  field :grades, :type => Hash, :default => {}
  field :dirty_grade, :type => Boolean

  validates_presence_of :course_id, :name, :point_value

  #default_scope asc(:created_at)

  #Mongoid won't give me changes to arrays?
  #It sucks because I'm going to have to store a bool
  
  def update_grade(student_id, grade)
    grades[student_id.to_s] = grade
    save
  end

  def calculate_average
    if(dirty_grade)
      total_grade=0.0
      valid_grades=0
      self.grades.each_key do |student_id|
        if(grades[student_id][0].is_a?(Numeric) )
          total_grade += grades[student_id][0]
          valid_grades += 1
        end
      end
      if valid_grades != 0
        self.average = percentage(((total_grade / point_value) / valid_grades) * 100)
      else
        self.average = "no_grades"
      end
      self.dirty_grade = false
      self.save
    end
  end

  def graded?(student_id)
    grade = grades[student_id.to_s]
    if !grade
      return false
    else
      if grade[0] == :ungraded
        return false
      end
      return true
    end
  end

  #Assumes that grade entry exists for student id
  def grade_percentage(student_id)
    grade = grades[student_id.to_s][0]
    return percentage((grade * 100)/point_value)
  end

  def teacher_comment(student_id)
    comment = grades[student_id.to_s][1]
    if comment != :nocomment
      return comment
    else return false
    end
  end

  #Properly formatted array to display in the student view
  #Assumes that the grade actually exists
  def graph_array(student_id)
    grade = (self.grades[student_id.to_s][0].to_f / self.point_value) * 100
    return {:name => self.name, :x => date_due.to_time.to_i * 1000, :y => '%2.f' % grade}
  end

  private
  def percentage(number)
    return number_to_percentage(number, :precision => 2, :strip_insignificant_zeros => true)
  end

end

app/models/assignment_type.rb
class AssignmentType
  include Mongoid::Document
  DEFAULT_ASSIGNMENTS = ["Homework", "Quiz", "Test", "Project"]

  before_destroy :validate_no_assignments
  
  cache

  has_many :assignments
  belongs_to :gradebook_settings, :class_name => "GradebookSettings"

  validates_presence_of :course_id

  field :course_id, :type => Integer
  field :name, :type => String
  field :weight, :type => Integer

  private
  def validate_no_assignments
    if self.assignments.count > 0
      return false
    end
    return true
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  #GET /gradebooks/:course_id/:assignment_id

  def edit
    @assignment = Assignment.find(params[:assignment_id])
    @types = AssignmentType.where(:course_id => params[:course_id])
    respond_to do |format|
      format.html {render :layout => false}
    end
  end

  def show
    @assignment = Assignment.find(params[:id])
    @assignment.calculate_average
    respond_to do |format|
      format.html {render :layout => false}
      format.json {render :json => @assignment}
    end
  end

    def update
    puts params
    @assignment = Assignment.find(params[:assignment][:id])
    @assignment.dirty_grade = true;
    respond_to do |format|
      if @assignment.update_attributes!(params[:assignment])
        format.js
      else
        format.js
      end
    end
  end

  def new
    @course = Course.find(params[:course_id])
    @assignment = Assignment.new
    @types = AssignmentType.where(:course_id => params[:course_id])
    respond_to do |format|
      format.html {render :layout => false}
    end
  end

  def create
    @assignment = Assignment.new(params[:assignment])
    @string = @assignment.course_id.to_s
    respond_to do |format|
      if @assignment.save
        format.html
        format.js
      else
        format.html
        format.js
      end
    end
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @grade_id = @assignment.id
    respond_to do |format|
      format.js
    end
    @assignment.destroy
  end

  #Updating individual grade
  def update_assignment_grade
    @assignment = Assignment.find(params[:id])
    id = params[:student_id]
    if !@assignment.grades[id.to_s]
      @assignment.grades[id.to_s] = [:ungraded, :nocomment]
      @assignment.save
    end

    grade_value = params[:value]
    
    if grade_value != ""
      if grade_value == "EX" || grade_value == "IN" || grade_value == "DR"
        @assignment.grades[id.to_s][0] = grade_value
      else
        if (grade_value.to_f % 1 != 0.0)
          @assignment.grades[id.to_s][0] = params[:value].to_f
        else
          @assignment.grades[id.to_s][0] = params[:value].to_i
        end
      end
    else
      @assignment.grades[id.to_s][0] = :ungraded
    end

    #This is unfortunately necessary due to a Mongoid bug
    array = @assignment.grades[id.to_s]
    @assignment.grades[id.to_s] = nil
    @assignment.save :validate => false
    @assignment.grades[id.to_s] = array
    @assignment.update_attributes!(:dirty_grade => true)
    @assignment.save :validate => false
    puts @assignment.dirty_grade

    @returned = params[:value]
    respond_to do |format|
      format.html {render :layout => false}
    end
  end

  def grade_report
    @assignment = Assignment.find(params[:id])
    respond_to do |format|
      format.html {render :layout => false}
    end
  end

  def comment_submit
    @assignment = Assignment.find(params[:id])
    id = params[:student_id]
    if !@assignment.grades[id.to_s]
      @assignment.grades[id.to_s] = [:ungraded, :nocomment]
      @assignment.save
    end

    if params[:value] != ""
      @assignment.grades[id.to_s][1] = params[:value]
    else
      @assignment.grades[id.to_s][1] = :nocomment
    end

    #Unfortunately necessary due to a mongoid bug
    array = @assignment.grades[id.to_s]
    @assignment.grades[id.to_s] = nil
    @assignment.save :validate => false
    @assignment.grades[id.to_s] = array
    @assignment.save :validate => false

    respond_to do |format|
      format.html {render :text => ""}
    end
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
  def id_to_link
    return "/gradebooks/" + @assignment.course_id.to_s + '/' + @assignment.id.to_s + '/edit'
  end

  def test_helper(test_var)
    return number_to_percentage(test_var)
  end

end

app/views/assignments/_graph.html.erb
<script type="text/javascript" charset="utf-8">
  var length = student_names.length;
  var series_array = [];
  var point_value = <%= @assignment.point_value %>
  <% @assignment.grades.each_key do |student_id| %>
    <% current_grade = @assignment.grades[student_id][0] %>
    <% if current_grade != :ungraded %>
      <% calculated_grade = (current_grade.to_f / @assignment.point_value) * 100 %> 
      var grade_value = (<%= calculated_grade %>);
      series_array.push({name: student_names["<%= student_id %>"] + ",<%= current_grade %>", data: <%= '%.2f' % calculated_grade %>});
    <% end %>
  <% end %>
  series_array.sort(series_comparator);
  chart1 = new Highcharts.Chart({
         chart: {
            renderTo: 'container',
            type: 'column',
            borderRadius: 0
         },
         tooltip: {
           formatter: function(){
              var name = this.series.name.split(',');
              return name[0] + '<br/>' + this.y + 
              "% (" + name[1] + "/" + point_value + ")";
           }
         },
         credits: {
           enabled: false
         },
         legend: {
           enabled: false
         },
         title: {
            text: '<%= @assignment.name %> Grades'
         },
         xAxis: {
          allowDecimals: false,
          labels:{
            enabled: false
          }
         },
         yAxis: {
            title: {
               text: 'Grade'
            },
            labels:{
              formatter: function(){
                return "" + this.value + "%";
              }
            }
         },
         plotOptions: {
           series: {
             color: '#FF0000'
           }
         },
         series: series_array
      });
</script>
<div id="container"></div>

app/views/assignments/create.js.erb
destroy_table();

created_assignment = new_assignment("<%= @assignment.id %>", <%= @assignment.point_value %>, "<%= @assignment.assignment_type_id %>");
assignments_array.push(created_assignment);

$('.datatable').attr('width', new_table_width());

var header_html = "<th class='assignment_header' align='left' id=<%=@assignment.id%>>";
header_html += "<span class='ui-icon-info hover_button' float='right' title='info'></span>";
header_html += "<p class='assignment-name' display='inline' padding='0' margin-top='0'>" + "<%=@assignment.name%>" + "</p></th>"

$(header_html).insertAfter($('.header_row th:last'));

var student_count=0;

var student_rows = $(".datatable .row_entry");
var length = student_rows.length;
var new_cell = $("<td align='center' class='grade_entry'></td>");
while(length--){
  $(student_rows[length]).append(new_cell.clone());
  student_count++;
}

initTable(student_count);

resize_datatable();
$('.dataTables_scroll .datatable').attr('style', "");
init_headers();

app/views/assignments/destroy.js.erb
remove_assignment("<%= @grade_id %>");
console.log($('.dataTables_scroll'));
$('.dataTables_scroll .datatable').width(function(index, value){
  return (assignments_array.length * 150);
});
//this is incredibly ghetto...we'll have to read to find where this damn thing is placed
//$('.dataTables_scroll').attr('style', "");
$('.dataTables_scrollBody .datatable tbody tr').each(function(){
  $(this).children()[position].html("");
  var grade = calculateGrade(this);
  apply_grade(this, grade);
}); 
//fnUpdate can be made faster. Look into this later

app/views/assignments/edit.html.haml
:javascript
  $(document).ready(function() {
    $('#assignment_date_due').datepicker({ dateFormat: 'yy-mm-dd' });
    $('#edit_assignment').bind('submit', function(){
      $.post('/assignments/update.js', $(this).serialize(), null, "script");
      closeBox();
      return false;
    });

    $('#delete_assignment').bind('click', function(){
      $.post('/assignments/#{@assignment.id}', { _method: 'delete'}, null, "script");
      closeBox();
      return false;
    });

    $("#submit_edit_assignment").click(function(){
      $("#edit_assignment").submit();
    });

  }); 

%div{:class => "overview-info fg-toolbar ui-toolbar ui-widget-header ui-helper-clearfix"}="Edit Assignment"
%br
=form_for @assignment, :remote => true, :html => {:method => :post, :id => "edit_assignment"} do |f|
  =f.hidden_field :id, :value => params[:assignment_id] 
  =f.hidden_field :course_id, :value => params[:course_id]
  %div{:class => "field"}
    =f.label :name
    %br
    =f.text_field :name, :value => @assignment.name
  %div{:class => "field"}
    =f.label :assignment_type_id, "Assignment Type"
    %br
    =collection_select(:assignment, :assignment_type, @types, :id, :name, {:selected => @assignment.assignment_type.id});
  %div{:class => "field", :style => "margin-top:10px;"}
    =f.label :point_value, "Point Value"
    =f.text_field :point_value, :value => @assignment.point_value
  %div{:class => "field", :style => "margin-top:10px;"}
    =f.label :date_due, "Date Due"
    =f.text_field :date_due, :value => @assignment.date_due
  %div{:class => "new_assignment_buttons"}
    %button{:id => "delete_assignment", :class => "button", :value => "Delete Assignment", :float => "left"}="Delete"
    %button{:type => "button", :class => "button", :id => "submit_edit_assignment"}="Update"
    =close_openBox_button

app/views/assignments/grade_report.html.haml
:javascript
  $(document).ready(function(){
  });

=render :partial => "graph"

%div{:align => "right"}
  =close_openBox_button

app/views/assignments/index.html.haml
%table
  -@assignments.each do |assignment|
    %tr
      %td=assignment.name

=link_to 'New Assignment', new_assignment_path

app/views/assignments/new.html.haml
:javascript
  $(document).ready(function() {
    $('#cert_alert').hide();
    $('#assignment_date_due').datepicker({ dateFormat: 'yy-mm-dd' });
    $('.new_assignment').bind('submit', function(){
      $.post($(this).attr("action") + '.js', $(this).serialize(), null, "script");
      closeBox();
      return false;
    });

    $("#submit_new_assignment").click(function(){
      if(validate_new_assignment()){
        $(".new_assignment").submit();
      }
      else{
        return false;
      }
    });
  }); 

%div{:class => "scale-header overview-info fg-toolbar ui-toolbar ui-widget-header ui-helper-clearfix"}="New Assignment"
%div{:id => "cert_alert"}
=form_for @assignment, :html => {:id => "new_assignment"} do |f|
  =f.hidden_field :course_id, :value => params[:course_id]
  %div{:class => "field"}
    =f.label :name, "Name:", {:class => "new_assignment_labels"}
    %br
    =f.text_field :name
  %div{:class => "field", :style => "margin-top:10px;"}
    =f.label :assignment_type_id, "Assignment Type:"
    %br
    =collection_select(:assignment, :assignment_type, @types, :id, :name, {});
  %div{:class => "field", :style => "margin-top:10px;"}
    =f.label :point_value, "Point Value: ", {:class => "new_assignment_labels"}
    =f.text_field :point_value
  %div{:class => "field", :style => "margin-top:10px;"}
    =f.label :date_due, "Date Due:", {:class => "new_assignment_labels"}
    =f.text_field :date_due 
  %div{:class => "new_assignment_buttons"}
    %button{:type => "button", :class => "button", :id => "submit_new_assignment"}="Submit"
    =close_openBox_button
    

app/views/assignments/show.html.haml
:javascript
  $(document).ready(function(){
    $(".edit_assignment").bind('click', function(){
      openBox("#{id_to_link}", 300);
    });

    $(".visualize").click(function(){
      openBox("/gradebooks/assignments/#{@assignment.id}/report", 350);
    });
  });
%div{:id => "show_buttons", :float => "right", :align => "right"}
  %button{:type => "button", :class => "visualize"}="Graph"
  %br
  %button{:type => "button", :class => "edit_assignment"}="Edit"
%div{:id => "assignment-stats"}
  =@assignment.name
  %br
  =@assignment.assignment_type.name
  %br
  -unless @assignment.average == "no_grades"
    ="Average: " + @assignment.average.to_s

app/views/assignments/update.js.erb
update_assignment("<%= @assignment.id %>", <%= @assignment.point_value %>, "<%= @assignment.name %>");

app/views/assignments/update_assignment_grade.html.haml
=@returned