config/routes.rb
Gradebook::Application.routes.draw do
  match 'reporting/:course_id' => 'reporting#show'
  
  get "courses/index"

  match 'gradebooks/:course_id/table' => 'gradebooks#table'
  match 'submit_grade' => 'assignment_grades#submit'

  resources :grade_scales
  resources :courses
  resources :gradebook_settings

  match 'gradebooks/:course_id', :to => 'gradebooks#show'
  match 'gradebooks/:course_id/assignments', :to => "assignments#new"
  resources :assignment_grades
  resources :assignments, :except => [:index]
  match 'assignments/update/' => 'assignments#update', :via => :post

  match 'gradebooks/:course_id/assignments/update' => 'assignments#update' , :via => :post
  match 'gradebooks/:course_id/:assignment_id/edit' => 'assignments#edit'
  match 'gradebooks/:course_id/report' => 'gradebooks#report'

  match 'gradebooks/grading_scale/:course_id' => 'grade_scales#scale'
  match 'gradebooks/assignments/:id/update' => 'assignments#update_assignment_grade', :via => :put
  match 'gradebooks/assignments/:id/report' => 'assignments#grade_report'
  match 'gradebooks/assignments/:id/comment' => 'assignments#comment_submit', :via => :put
  match 'gradebooks/assignments/:id/manual_grade' => 'grade_scales#grade', :via => :put
  match 'gradebooks/:course_id/weight' => 'gradebooks#weight'
  match 'gradebooks/settings/:settings_id/weight' => 'gradebook_settings#update_weight', :via => :put

  match 'gradebooks/:course_id/student/:student_id' => 'gradebooks#student_view'

  match 'gradebooks/:course_id/:student_id/course_grade' => 'gradebooks#update_course_grade', :via => :put

  match 'attendance/:course_id/student/:student_id/:date', :to => "attendance_records#update_student", :via => :post, :as => "update_student_attendance"
  match 'attendance/:course_id/student/:student_id/', :to => "attendance_records#student_record", :via => :get, :as => "student_attendance"
  match 'attendance/:course_id(/:date)', :to => "attendance_records#show", :as => "course_attendance"

end

app/models/assignment_grade.rb
class AssignmentGrade
  include Mongoid::Document
  include Mongoid::Timestamps
#belongs_to :student, :class_name => :User, :foreign_key => "uid"
#TODO: Fix relations when Mongoid team adds support for relations with AR objects
  
  scope :by_date, desc(:created_at)

  belongs_to :assignment
  field :student_id, :type => Integer
  field :course_id, :type => Integer

#TODO: Support for "letter grades"
  field :value, :type => Integer, :default => 0
  field :graded, :type => Boolean, :default => false

  key :student_id, :assignment_id

  def dirty_parent
    self.assignment.write_attributes(:dirty_grade => true)
    self.assignment.save
  end

end

app/views/assignment_grades/_form.html.erb
<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignment_grades/edit.html.erb
<h1>Editing grade</h1>

<%= render 'form' %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', assignment_grades_path %>

app/views/assignment_grades/index.html.erb
<h1>Listing grades</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @grades.each do |grade| %>
  <tr>
    <td><%= link_to 'Show', assignment_grade %></td>
    <td><%= link_to 'Edit', edit_assignment_grade_path(grade) %></td>
    <td><%= link_to 'Destroy', assignment_grade, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grade', new_assignment_grade_path %>

app/views/assignment_grades/new.html.erb
<h1>New grade</h1>

<%= render 'form' %>

<%= link_to 'Back', assignment_grades_path %>

app/views/assignment_grades/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_assignment_grade_path(@grade) %> |
<%= link_to 'Back', assignment_grades_path %>

app/views/assignment_grades/submit.html.haml
=@returned