config/routes.rb
Gradebook::Application.routes.draw do
  match 'reporting/:course_id' => 'reporting#show'
  
  get "courses/index"

  match 'gradebooks/:course_id/table' => 'gradebooks#table'
  match 'submit_grade' => 'assignment_grades#submit'

  resources :grade_scales
  resources :courses
  resources :gradebook_settings

  match 'gradebooks/:course_id', :to => 'gradebooks#show'
  match 'gradebooks/:course_id/assignments', :to => "assignments#new"
  resources :assignment_grades
  resources :assignments, :except => [:index]
  match 'assignments/update/' => 'assignments#update', :via => :post

  match 'gradebooks/:course_id/assignments/update' => 'assignments#update' , :via => :post
  match 'gradebooks/:course_id/:assignment_id/edit' => 'assignments#edit'
  match 'gradebooks/:course_id/report' => 'gradebooks#report'

  match 'gradebooks/grading_scale/:course_id' => 'grade_scales#scale'
  match 'gradebooks/assignments/:id/update' => 'assignments#update_assignment_grade', :via => :put
  match 'gradebooks/assignments/:id/report' => 'assignments#grade_report'
  match 'gradebooks/assignments/:id/comment' => 'assignments#comment_submit', :via => :put
  match 'gradebooks/assignments/:id/manual_grade' => 'grade_scales#grade', :via => :put
  match 'gradebooks/:course_id/weight' => 'gradebooks#weight'
  match 'gradebooks/settings/:settings_id/weight' => 'gradebook_settings#update_weight', :via => :put

  match 'gradebooks/:course_id/student/:student_id' => 'gradebooks#student_view'

  match 'gradebooks/:course_id/:student_id/course_grade' => 'gradebooks#update_course_grade', :via => :put

  match 'attendance/:course_id/student/:student_id/:date', :to => "attendance_records#update_student", :via => :post, :as => "update_student_attendance"
  match 'attendance/:course_id/student/:student_id/', :to => "attendance_records#student_record", :via => :get, :as => "student_attendance"
  match 'attendance/:course_id(/:date)', :to => "attendance_records#show", :as => "course_attendance"

end

app/models/attendance_record.rb
class AttendanceRecord
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :course_id, :type => Integer
  field :date, :type => Date
  
  # The cases hash is a list of all students that ARE either abset or tardy for
  # The given date. The key for the hash is the student's id, the value is
  # either :absent or :tardy 
  field :cases, :type => Hash, :default => {}
  
  cache
  
  def course
    Course.find(course_id)
  end
  
  def student_absent?(student)
    return cases[student.id.to_s] == :absent
  end
  
  def student_tardy?(student)
    return cases[student.id.to_s] == :tardy
  end
end

app/controllers/attendance_records_controller.rb
class AttendanceRecordsController < ApplicationController
  # GET /attendance_records/1
  # GET /attendance_records/1.json
  def show
    @from_ajax = !(params[:tableonly].nil?)
    @course = Course.find(params[:course_id])
    if params[:date].nil?
      @date = Date.today
    else
      @date = Date.strptime(params[:date],"%Y-%m-%d")
    end
    @students = @course.students
    @attendance_record = AttendanceRecord.find_or_create_by(:course_id => @course.id, :date => @date)
    @dtlength = @students.count
    respond_to do |format|
      format.html # show.html.erb
    end
  end
  
  def student_record
    @course = Course.find(params[:course_id])
    @student = User.find(params[:student_id])
    @records = AttendanceRecord.where(:course_id => params[:course_id]).any_in("cases."+@student.id_s => [:absent,:tardy]).order_by([:date,:desc])
    respond_to do |format|
      format.html { render :layout => false }
    end
  end
  
  def update_student
    @course = Course.find(params[:course_id])
    @date = Date.strptime(params[:date],"%Y-%m-%d")
    @attendance_record = AttendanceRecord.find_or_create_by(:course_id => @course.id, :date => @date)
    if params[:type] == "absent"
      if @attendance_record.cases[params[:student_id]] == :absent
        @attendance_record.cases.delete(params[:student_id])
      else
        @attendance_record.cases[params[:student_id]] = :absent
      end
    end
    if params[:type] == "tardy"
      if @attendance_record.cases[params[:student_id]] == :tardy
        @attendance_record.cases.delete(params[:student_id])
      else
        @attendance_record.cases[params[:student_id]] = :tardy
      end
    end
    @attendance_record.save
    render :text => "ok"
  end
end

app/helpers/attendance_records_helper.rb
module AttendanceRecordsHelper
  def table_element(containing_text, options = {})
    options.reverse_merge! :id => "", :onclick => "", :data_cache => "", :class => ""
    td =  '<td ' 
    td += 'id="'+options[:id]+'" '
    td += 'class="'+options[:class]+'" '
    td += 'onclick="'+options[:onclick]+'" '
    td += 'align="center" '
    td += 'data-cache="'+options[:data_cache]+'" '
    td += 'style="padding:10px 8px;"'
    td += '>'+containing_text+'</td>'
    td.html_safe
  end
  
  def checkbox_element(onclickjs, options = {})
    options.reverse_merge! :checked => false, :id => ""
    input  = '<input '
    input += 'type="checkbox"'
    input += 'id="'+options[:id]+'" '
    input += 'onclick="'+onclickjs+'" '
    if options[:checked]
      input += 'checked '
    end
    input += '/>'
    table_element(input.html_safe).html_safe
  end
end

app/views/attendance_records/show.html.erb
<% if @from_ajax %>
  <script>
    _date = '<%= @date %>';
    make_attendance_table($('#attendance_table'));
  </script>
<% else %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application" %>
  <script>
  	var _oTable;
  	var _date = '<%= @date %>';
  	$(document).ready(function(){
  		make_attendance_table($('#attendance_table'));
  	});
  	
  	function make_attendance_table(table)
  	{
  	  var checkboxParamObject = {sWidth:"20px", bSearchable:false, bSortable:false};
			var namesParamObject = {sType:"string"};
			var numberParamObject = {sType:"numeric", sWidth:"85px", bSearchable:false};
			_oTable = table.dataTable({
				aoColumns:[
					checkboxParamObject,
					checkboxParamObject,
					namesParamObject,
					namesParamObject,
					numberParamObject,
					numberParamObject,
					{sType:"date",sDefaultContent:"none",sWidth:"90px",bSearchable:false}
				],
				sDom:'<"H"rf<"#date_wrapper"<"#current_date">>>t<"F">',
				<% if !@dtlength.nil? %>
				iDisplayLength: <%= @dtlength %>,
				<% end %>
				bAutoWidth: false
			});
			$("#date_wrapper").css("float","right");
  		$("#date_wrapper").append('<button class="button" onclick="gototoday()">today</button><span>&nbsp;</span>');
  		$("#date_wrapper").append('<label>Go to date: <input id="datepicker" type="text" /></label>');
  		$("#datepicker").datepicker({
  			dateFormat:"yy-mm-dd",
  			onSelect:function(dateText,inst){
  			  var url = '<%= course_attendance_path(@course,"'+dateText+'") %>'
  				//  window.location.href = url;
  				get_table_from_url(url);
  			}
  		});
  		$("#current_date").text(formatDate(new Date(_date),"NNN dd, yyyy"));
  	}

  	/*/
  	 *	Functions for grabbing HTML elements
  	/*/
  	function row(student)
  	{
  		return $("#"+student);
  	}

  	function checkbox(student,type)
  	{
  		return $("#"+type+"_"+student)[0];
  	}

  	function count_box(student,type)
  	{
  		return $("#"+student+"_"+type+"_count");
  	}

  	/*/
  	 *	Main function that updates all the boxes that need it
  	/*/
  	function update(student,type)
  	{
  		type = (type == 1 ? "absent" : "tardy");
  		var antitype = (type == "absent" ? "tardy" : "absent");
  		if(checkbox(student,antitype).checked)
  			decrement_count_box(count_box(student,antitype))
  		checkbox(student,antitype).checked = false;
  		if(checkbox(student,type).checked)
  			increment_count_box(count_box(student,type));
  		else
  			decrement_count_box(count_box(student,type));
  		update_row_styling(student,type);
  		update_last_date(student);
  		update_server(student,{type:type});
  	}

  	/*/
  	 *	Helper functions
  	/*/
  	function increment_count_box(box)
  	{
  		set_cell_text(box,parseInt(box.text()) + 1);
  	}

  	function decrement_count_box(box)
  	{
  		set_cell_text(box,parseInt(box.text()) - 1);
  	}

  	function update_last_date(student)
  	{
  		var box = $("#"+student+"_last_violation"),
  				current = box.text(),
  				today = new Date(_date),
  				acb = checkbox(student,"absent"),
  				tcb = checkbox(student,"tardy");
  		if(box.data("cache") == "")
  			box.data("cache", box.text());
  		if((acb.checked || tcb.checked) && (current == "none" || today > new Date(current)))
  			set_cell_text(box,formatDate(today,"MM-dd-yyyy"));
  		if(!acb.checked && !tcb.checked)
  			set_cell_text(box,box.data("cache"))
  	}

  	function set_cell_text(cell,text)
  	{
  		//	Update datatables
  		if(_oTable)
  		{
  			var pos = _oTable.fnGetPosition(cell[0]);
  			_oTable.fnUpdate(text,pos[0],pos[1],false);
  		}
  		cell.text(text);
  	}

  	function update_row_styling(student,type)
  	{
  		row(student).removeClass("absent tardy");
  		if(checkbox(student,type).checked)
  			row(student).addClass(type);
  	}

  	function update_server(student,data)
  	{
  		var url = '<%= update_student_attendance_path(@course,"'+student+'","'+_date+'") %>';
  		$.ajax(url,{
  			type:"post",
  			data:data
  		});
  	}
	
  	function view_student(student)
  	{
  		var url = '<%= student_attendance_path(@course,"'+student+'")%>';
  		openBox(url,350,0);
  	}
	
  	function gotodate(date)
  	{
  		var url = '<%= course_attendance_path(@course,"'+date+'") %>';
//  		window.location.href = url;
      get_table_from_url(url);
  	}
	
  	function gototoday()
  	{
  		var url = '<%= course_attendance_path(@course) %>';
//  		window.location.href = url;
  		get_table_from_url(url);
  	}
  	
  	function get_table_from_url(url)
  	{
  	  url += "?tableonly=true";
  	  $("#attendance_table_wrap").html('<img src="/app/core/site_img/loading.gif" />');
  	  $.ajax(url,{
  	    success:function(data){
  	      $("#attendance_table_wrap").html(data);
  	    }
  	  });
  	}

  </script>
  <div id="attendance_table_wrap">
<% end %>
  <table id="attendance_table" class="attendance" style="width:100%;">
  	<thead>
  		<tr>
  			<th class="absent">A</th>
  			<th class="tardy">T</th>
  			<th>First name</th>
  			<th>Last name</th>
  			<th>Absent</th>
  			<th>Tardy</th>
  			<th>Last</th>
  		</tr>
  	</thead>
  	<tbody>
  		<% @students.each do |student| %>
  			<% if student.is_student? %>
  				<tr id="<%= student.id.to_s %>" class="<%= @attendance_record.cases[student.id.to_s].to_s %>">
  					<% last_case = student.last_day_absent_or_tardy(@course) %>
  					<% cache = (last_case == @date ? student.second_to_last_day_absent_or_tardy(@course) : "") %>
  					<%= checkbox_element('update('+student.id.to_s+',1);', :checked => @attendance_record.student_absent?(student), :id => "absent_"+student.id.to_s) %>
  					<%= checkbox_element('update('+student.id.to_s+',2);', :checked => @attendance_record.student_tardy?(student), :id => "tardy_"+student.id.to_s) %>
  					<%= table_element(student.first_name.capitalize, :onclick => "view_student("+student.id_s+")", :class => "hoverable") %>
  					<%= table_element(student.last_name.capitalize, :onclick => "view_student("+student.id_s+")", :class => "hoverable") %>
  					<%= table_element(student.days_absent_for_course(@course).count.to_s, :id => student.id_s+"_absent_count") %>
  					<%= table_element(student.days_tardy_for_course(@course).count.to_s, :id => student.id_s+"_tardy_count") %>
  					<%= table_element(last_case.nil? ? "none" : last_case.strftime("%m-%d-%Y"), :id => student.id_s+"_last_violation", :data_cache => cache) %>
  				</tr>
  			<% end %>
  		<% end %>
  	</tbody>
  </table>
<% if !@from_ajax %>
  </div>
<% end %>

app/views/attendance_records/student_record.html.erb
<div class="overview-info fg-toolbar ui-toolbar ui-widget-header ui-helper-clearfix"><%= @student.capitalized_name %></div>
<div class="student_wrapper">
	<table class="overview">
		<thead>
			<tr>
				<td class="absent">absent</td>
				<td class="tardy">tardy</td>
				<td class="last">last</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @student.days_absent_for_course(@course).count %></td>
				<td><%= @student.days_tardy_for_course(@course).count %></td>
				<% last = @records.first %>
				<% number = (last.nil? ? 0 : (Date.today-last.date).to_i)%>
				<td><%= last.nil? ? "never" : number %><span class="days"> day<%= (number != 1) ? "s" : "" %></span></td>
			</tr>
		</tbody>
	</table>
	<h4>Attendance Log</h4>
	<% if @records.count > 0 %>
		<table class="log">
			<tbody>
				<% @records.each do |record| %>
					<tr class="<%= record.cases[@student.id_s] == :absent ? "absent" : "tardy" %>">
						<td class="initial" style="width:30px"><%= record.cases[@student.id_s] == :absent ? "A" : "T" %></td>
						<td class="date" onclick="gotodate('<%= record.date.strftime("%Y-%m-%d") %>'); closeBox();"><%= record.date.strftime("%m-%d-%Y") %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% else %>
		<p><%= @student.first_name.capitalize %> has never missed a class</p>
	<% end %>
	<div style="margin-top:10px; margin-bottom:20px;">
		<!--<button class="action" onclick="print();">Print</button>-->
		<button class="button" onclick="closeBox();" style="float:right; margin-bottom:5px;">Close</button>
	</div>
</div>