config/routes.rb
Gradebook::Application.routes.draw do
  match 'reporting/:course_id' => 'reporting#show'
  
  get "courses/index"

  match 'gradebooks/:course_id/table' => 'gradebooks#table'
  match 'submit_grade' => 'assignment_grades#submit'

  resources :grade_scales
  resources :courses
  resources :gradebook_settings

  match 'gradebooks/:course_id', :to => 'gradebooks#show'
  match 'gradebooks/:course_id/assignments', :to => "assignments#new"
  resources :assignment_grades
  resources :assignments, :except => [:index]
  match 'assignments/update/' => 'assignments#update', :via => :post

  match 'gradebooks/:course_id/assignments/update' => 'assignments#update' , :via => :post
  match 'gradebooks/:course_id/:assignment_id/edit' => 'assignments#edit'
  match 'gradebooks/:course_id/report' => 'gradebooks#report'

  match 'gradebooks/grading_scale/:course_id' => 'grade_scales#scale'
  match 'gradebooks/assignments/:id/update' => 'assignments#update_assignment_grade', :via => :put
  match 'gradebooks/assignments/:id/report' => 'assignments#grade_report'
  match 'gradebooks/assignments/:id/comment' => 'assignments#comment_submit', :via => :put
  match 'gradebooks/assignments/:id/manual_grade' => 'grade_scales#grade', :via => :put
  match 'gradebooks/:course_id/weight' => 'gradebooks#weight'
  match 'gradebooks/settings/:settings_id/weight' => 'gradebook_settings#update_weight', :via => :put

  match 'gradebooks/:course_id/student/:student_id' => 'gradebooks#student_view'

  match 'gradebooks/:course_id/:student_id/course_grade' => 'gradebooks#update_course_grade', :via => :put

  match 'attendance/:course_id/student/:student_id/:date', :to => "attendance_records#update_student", :via => :post, :as => "update_student_attendance"
  match 'attendance/:course_id/student/:student_id/', :to => "attendance_records#student_record", :via => :get, :as => "student_attendance"
  match 'attendance/:course_id(/:date)', :to => "attendance_records#show", :as => "course_attendance"

end

app/models/grade_scale.rb
class GradeScale
  include Mongoid::Document
  
  MODE_SCALE = "scale"
  
  DEFAULT_SCALE = [{:from => 0,:to => 59, :name =>"F"}, {:from=>60,:to=>69,:name=>"D"}, {:from=>70,:to =>79,:name =>"C"}, {:from =>80,:to=>89,:name=>"B"},{:from=>90,:to=>100,:name=>"A"}]

  field :course_id, :type => Integer
  field :scale_type, :type => String, :default => "scale"
  field :manual_grades, :type => Hash, :default => {}

  belongs_to :gradebook_settings, :class_name => "GradebookSettings"
  embeds_many :grade_ranges
  after_create :init_default_scale
  accepts_nested_attributes_for :grade_ranges, :allow_destroy => true
  validates_presence_of :course_id

  def init_default_scale
    DEFAULT_SCALE.each do |range|
      grade_ranges.create!(:from => range[:from], :to => range[:to], :name => range[:name])
    end
  end

  def update_manual_grade(student_id, grade)
    manual_grades[student_id.to_s] = grade
    save :validate => false
  end

end

app/controllers/grade_scales_controller.rb
class GradeScalesController < ApplicationController
  # GET /grade_scales
  # GET /grade_scales.json
  def index
    @grade_scales = GradeScale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @grade_scales }
    end
  end

  def scale
    @scale = GradeScale.where(:course_id => params[:course_id]).first
    respond_to do |format|
      format.html {render :layout => false}
    end
  end

  # GET /grade_scales/1
  # GET /grade_scales/1.json
  def show
    @scale = GradeScale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @grade_scale }
    end
  end

  # GET /grade_scales/new
  # GET /grade_scales/new.json
  def new
    @grade_scale = GradeScale.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @grade_scale }
    end
  end

  # GET /grade_scales/1/edit
  def edit
    @grade_scale = GradeScale.find(params[:id])
  end

  # POST /grade_scales
  # POST /grade_scales.json
  def create
    @grade_scale = GradeScale.new(params[:grade_scale])

    respond_to do |format|
      if @grade_scale.save
        format.json { render :json => @grade_scale, :status => :created, :location => @grade_scale }
      else
        format.json { render :json => @grade_scale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /grade_scales/1
  # PUT /grade_scales/1.json
  def update
    @grade_scale = GradeScale.find(params[:id])
    respond_to do |format|
      if(params[:grade_scale][:scale_type] != "manual")
          @grade_scale.manual_grades.clear
      end
      if @grade_scale.update_attributes(params[:grade_scale])
        format.js
      end
    end
  end

  # DELETE /grade_scales/1
  # DELETE /grade_scales/1.json
  def destroy
    @grade_scale = GradeScale.find(params[:id])
    @grade_scale.destroy

    respond_to do |format|
      format.html { redirect_to grade_scales_url }
      format.json { head :ok }
    end
  end

  def grade
    @grade_scale = GradeScale.find(params[:id])
    @student_id = params[:student_id].to_s
    _grade = params[:value]

    @grade_scale.manual_grades[@student_id] = _grade
    @grade_scale.save

    respond_to  do |format|
      format.html {render :text => ""}
    end
  end

end

app/helpers/grade_scales_helper.rb
module GradeScalesHelper
end

app/views/grade_scales/_form.html.erb
<%= form_for(@grade_scale) do |f| %>
  <% if @grade_scale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade_scale.errors.count, "error") %> prohibited this grade_scale from being saved:</h2>

      <ul>
      <% @grade_scale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grade_scales/_grade_range_fields.html.haml
%tr{:class => "grade_detail_row"}
  %td=f.text_field :from, {:size => "1", :maxlength => "3"}
  %td{ :class => "operator" }=f.label :to,"to"
  %td=f.text_field :to, {:size => "1", :maxlength => "3"}
  %td{ :class => "operator" }=f.label "="
  %td=f.text_field :name, {:size => "2", :maxlength => "3"} 
  =f.hidden_field :_destroy, {:id => "range_destroy_field"}
  %td{ :class => "remove_button button" }=button_to_function "X", "remove_fields(this, 'range')"

app/views/grade_scales/edit.html.erb
<h1>Editing grade_scale</h1>

<%= render 'form' %>

<%= link_to 'Show', @grade_scale %> |
<%= link_to 'Back', grade_scales_path %>

app/views/grade_scales/index.html.erb
<h1>Listing grade_scales</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @grade_scales.each do |grade_scale| %>
  <tr>
    <td><%= link_to 'Show', grade_scale %></td>
    <td><%= link_to 'Edit', edit_grade_scale_path(grade_scale) %></td>
    <td><%= link_to 'Destroy', grade_scale, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grade scale', new_grade_scale_path %>

app/views/grade_scales/jic.html.haml
:javascript
  $(document).ready(function() {
    scale_type();
    $('#edit_scale').prepend('<div id="notice"></div>');
    $('#edit_scale').bind('submit', function(){
      $('#notice').hide();
      if(validate_scales_form()){
        $.post('/grade_scales/#{@scale.id}', $(this).serialize(), null, "script");
        closeBox();
        return false;
      }
      else{
        $('#notice').html('<h2>Grade ranges are busted.</h2>');
        $('#notice').show();
        return false;
      }
    });
  }); 

=form_for @scale, :remote => true, :html => {:id => "edit_scale", :method => "put"} do |s|
  %div{:id => "options"}
    %div{:id => "scale_button"}
      =s.radio_button :scale_type, :scale 
      =s.label :scale_type, "Scale"
    =s.radio_button :scale_type, :percentage
    =s.label :scale_type, "Percentage"
    %br
    =s.radio_button :scale_type, :manual
    =s.label :scale_type, "Manual"
  %div{:id => "range_fields"}
    -#Nested models ignore scope, so you need to do it as the second arg
    =s.fields_for :grade_ranges, @scale.grade_ranges.desc(:from) do |builder|  
      =render "grade_range_fields", :f => builder
  =s.submit
  =link_to_add_fields "Add Range", s, :grade_ranges
  =close_openBox_input

app/views/grade_scales/new.html.erb
<h1>New grade_scale</h1>

<%= render 'form' %>

<%= link_to 'Back', grade_scales_path %>

app/views/grade_scales/scale.html.haml
:javascript
  $(document).ready(function() {
    scale_mode_validate($('input[checked=checked]'));
    $('#edit_scale').bind('submit', function(){
      $('#cert_alert').hide();
      if($("input[type=radio]:checked").attr('value') === "scale"){
        if(validate_scales_form()){
          $.post('/grade_scales/#{@scale.id}', $(this).serialize(), null, "script");
          closeBox();
          return false;
        }
        else{
          return false;
        }
      }
      else{
       $.post('/grade_scales/#{@scale.id}', $(this).serialize(), null, "script");
       closeBox();
       return false; 
      }
    });

    $("#options").children().each(function(i,elem){
      $(elem).click(function(){
        $("#options").children().each(function(i,elem){
          $(elem).removeClass("selected");
          $(elem).find("input[type=radio]").attr("checked",false)
        });
        $(this).addClass("selected");
        var radio = $(this).find("input[type=radio]");
        radio.attr("checked",true);
        scale_mode_validate(radio);
      });
    });

    $("#submit_scale").click(function(){
      $("#edit_scale").submit();
    });

  }); 

%div{ :class => "scale-header fg-toolbar ui-toolbar ui-widget-header ui-helper-clearfix" }= "Change Grade Scale"
=form_for @scale, :remote => true, :html => {:id => "edit_scale", :method => "put"} do |s|
  %div{:id => "options"}
    %div{:class => (@scale.scale_type == "scale" ? "selected" : "")}
      =s.radio_button :scale_type, :scale, :style => "display:none"
      =s.label :scale_type, "Scale"
    %div{:class => (@scale.scale_type == "percentage" ? "selected" : "")}
      =s.radio_button :scale_type, :percentage, :style => "display:none"
      =s.label :scale_type, "Percentage"
    %div{:class => "last "+(@scale.scale_type == "manual" ? "selected" : "")}
      =s.radio_button :scale_type, :manual, :style => "display:none"
      =s.label :scale_type, "Manual"
  %div{:id => "cert_alert", :style => "display:none"}
  %div{:id => "range_fields", :style => ""}
    %table{:class => "grade_range"}
      -#Nested models ignore scope, so you need to do it as the second arg
      =s.fields_for :grade_ranges, @scale.grade_ranges.desc(:from) do |builder|  
        =render "grade_range_fields", :f => builder
      %tr{:class => "add_button_row"}
        %td{ :colspan => 6 }=link_to_add_fields("+ Add Range", s, :grade_ranges, "range")
  %div{:id => "scale_submission", :class => "scale-footer fg-toolbar ui-toolbar ui-widget-header ui-helper-clearfix"}
    %button{:type => "button", :class => "button", :id => "submit_scale"}="Submit"
    =close_openBox_button

app/views/grade_scales/show.html.haml
-@scale.grade_ranges.each do |scale|
  ="lol"

app/views/grade_scales/update.js.erb
grading_scale = <%= @grade_scale.grade_ranges.asc(:from).to_json(:except => [:_id]).html_safe %>;
grading_scale_method = "<%= @grade_scale.scale_type %>";
$('.dataTables_scrollBody .datatable tbody tr').each(function(){
  var grade = calculateGrade(this);
  apply_grade(this, grade);
});

if(grading_scale_method == "manual"){
  enable_editing();
}
else{
  disable_editing();
}